"""empty message

Revision ID: 190ccb439d34
Revises: 205dad0e9fe5
Create Date: 2020-11-22 17:23:05.522368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190ccb439d34'
down_revision = '205dad0e9fe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('creation_date', sa.DateTime(), nullable=True))
    op.execute('UPDATE "Artist" SET creation_date = Current_timestamp where creation_date is NULL;')
    op.alter_column('Artist', 'creation_date', nullable=False)
    op.add_column('Venue', sa.Column('creation_date', sa.DateTime(), nullable=True))
    op.execute('UPDATE "Venue" SET creation_date = Current_timestamp where creation_date is NULL;')
    op.alter_column('Venue', 'creation_date', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'creation_date')
    op.drop_column('Artist', 'creation_date')
    # ### end Alembic commands ###
