"""empty message

Revision ID: a4768095b88a
Revises: 190ccb439d34
Create Date: 2020-11-30 07:11:27.091407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4768095b88a'
down_revision = '190ccb439d34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking', sa.Boolean(), nullable=True))
    op.drop_column('Artist', 'seeking_venue')
    op.add_column('Venue', sa.Column('seeking', sa.Boolean(), nullable=True))
    op.drop_column('Venue', 'seeking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'seeking')
    op.add_column('Artist', sa.Column('seeking_venue', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'seeking')
    # ### end Alembic commands ###
