"""empty message

Revision ID: d810faf2564b
Revises: a4768095b88a
Create Date: 2020-11-30 17:34:34.013325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd810faf2564b'
down_revision = 'a4768095b88a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "Artist" ALTER COLUMN genres TYPE character varying[] USING genres::character varying(120)[];')
    # op.alter_column('Artist', 'genres',
    #            existing_type=postgresql.ARRAY(sa.VARCHAR(length=120)),
    #            type_=sa.ARRAY(sa.VARCHAR(length=120)),
    #            existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres',
               existing_type=sa.ARRAY(sa.Integer()),
               type_=postgresql.ARRAY(sa.VARCHAR(length=120)),
               existing_nullable=True)
    # ### end Alembic commands ###
