"""empty message

Revision ID: 7cfc083686a5
Revises: 89922a869a67
Create Date: 2020-12-27 17:29:16.629351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cfc083686a5'
down_revision = '89922a869a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tests_patient_id_fkey', 'tests', type_='foreignkey')
    op.create_foreign_key(None, 'tests', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.create_foreign_key('tests_patient_id_fkey', 'tests', 'patients', ['patient_id'], ['id'])
    # ### end Alembic commands ###
