"""empty message

Revision ID: 89922a869a67
Revises: 
Create Date: 2020-12-25 17:25:58.197030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89922a869a67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
